# Application Configuration
models:
  chat: gpt-4-1106-preview
  whisper: whisper-1
  tts: tts-1
  tts_voice: fable
  tts_speed: 1.0
  temperature: 0.7
  max_tokens: 4096

# Audio Settings
audio:
  input:
    device_index: 2            # TONOR TM20 Audio Device
    device_name: "TONOR TM20 Audio Device: USB Audio"
    native_rate: 48000         # Native sample rate of microphone (48kHz)
    processing_rate: 16000     # Required rate for Whisper/Porcupine
    channels: 1                # Mono audio input
    chunk_size: 1024          # Size of audio chunks to process
    buffer_size: 8192         # Audio buffer size
    pre_emphasis: 0.5         # High-frequency boost filter
    silence_threshold: 550    # Level below which is considered silence

  output:
    device_index: 1           # USB2.0 Device Audio
    device_name: "USB2.0 Device: Audio"
    rate: 48000              # Match input rate
    volume: 1.0              # Output volume multiplier
    chunk_size: 2048         # Output buffer size

# Wake Word Settings
wake_word:
  name: "hey messy"
  model_name: "hey-messy_en_raspberry-pi_v3_0_0.ppn"
  threshold: 0.85              # Picovoice recommended default
                             # Range: 0.0-1.0
                             # 0.0 = Least sensitive (fewer detections)
                             # 0.5 = Default balance
                             # 1.0 = Most sensitive (more detections)
  min_volume: 600            # Minimum volume to trigger detection
                            # Range: 0-32767 (16-bit audio RMS values)
                            # Set above ambient noise (~1.5x ambient)
  max_volume: 2000          # Maximum volume to consider
                           # Range: 0-32767 (16-bit audio RMS values)
                           # Set below clipping (~2x normal speech)
  detection_window: 2.0      # Time window to detect wake word (seconds)
  consecutive_frames: 1      # Required consecutive detections
  retry_count: 3            # Number of retries if detection fails

# Command Settings
command:
  min_duration: 0.5          # Minimum command duration (seconds)
  max_duration: 10.0         # Maximum command duration (seconds)
  min_volume: 90            # Minimum volume for command detection
  silence_timeout: 0.5      # Stop recording after silence duration
  pre_buffer: 0.1           # Audio to keep before command starts
  max_silence_chunks: 20    # Maximum silent chunks before stopping

# Logging Settings
logging:
  level: INFO
  file_rotation: "1 MB"
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Learning Settings
learning:
  enabled: true  # Toggle learning system on/off
  parameters:
    learning_rate: 0.1
    decay_factor: 0.95
    update_frequency: 3600
    min_samples: 10
  storage:
    data_path: "cache/learning/learning.json"
    config_path: "config/dynamic_config.yaml"
    logs_path: "logs/learning_updates.log"

# Notes:
# - All volume levels use RMS values from 16-bit audio (0-32767)
#   - Ambient noise: 200-800
#   - Normal speech: 500-2000
#   - Loud speech: 2000-4000
#   - Very loud/clipping: >4000
# - Calibrated using TONOR TM20 microphone with onboard DSP
# - Values may need adjustment if mic DSP behavior changes
# - Consider recalibrating if mic settings are modified
# - Monitor for over-filtering if both DSP and our filters are active
