# Application Configuration
models:
  chat: gpt-4-1106-preview
  whisper: whisper-1
  tts: tts-1
  tts_voice: alloy           # Faster voice
  tts_fallback: nova        # Fallback voice
  tts_speed: 1.0            # Normal speed (0.25 to 4.0)
  temperature: 0.7
  max_tokens: 150          # Reduced for concise responses

# Audio Settings (ALSA)
audio:
  input:
    # ALSA device settings
    device: "hw:CARD=Device_1,DEV=0"    # TONOR TM20 Audio Device (Card 4)
    format: "S16_LE"                    # 16-bit signed little-endian
    rate: 48000                         # Sample rate (48kHz)
    channels: 1                         # Mono input
    period_size: 2048                   # ALSA buffer period size
    
    # Processing settings
    processing_rate: 16000              # Rate for Whisper/Porcupine (16kHz)
    silence_threshold: 1285             # Volume level to detect silence
    silence_duration: 0.5               # Duration of silence to end recording (seconds)
    pre_emphasis: 0.5                   # High-frequency boost

  output:
    # ALSA device settings
    device: "plughw:CARD=Device,DEV=0"  # USB Speaker (Card 3)
    format: "S16_LE"                    # 16-bit signed little-endian
    rate: 48000                         # Sample rate (48kHz)
    channels: 1                         # Mono output
    period_size: 2048                   # ALSA buffer period size
    
    # Volume control
    volume: 1.0                         # Output volume multiplier

# Wake Word Settings
wake_word:
  name: "hey messy"
  model_path: "models/hey-messy_en_raspberry-pi_v3_0_0.ppn"
  sensitivity: 0.5                    # Detection sensitivity (0.0-1.0)
  
  # Volume thresholds
  volume_threshold: 1542              # Minimum volume for wake word detection
  max_volume: 5182                    # Maximum volume before clipping
  
  # Detection parameters
  detection_window: 1.0               # Time window in seconds
  consecutive_frames: 1               # Required detections
  retry_count: 5                      # Retries on failure

# Session Settings
session:
  require_reidentification: false     # Whether to verify user between sessions
  timeout: 300                        # Session timeout (5 minutes)
  max_turns: 10                       # Maximum conversation turns
  idle_timeout: 60                    # Idle timeout (1 minute)

# Speech Settings
speech:
  input_language: "en"                # Input language
  output_language: "en-US"            # Output language
  voice: "nova"                       # Primary TTS voice
  fallback_voice: "alloy"            # Fallback TTS voice
  model: "whisper-1"                  # Speech recognition model
  max_tokens: 150                     # Maximum response length
  temperature: 0.7                    # Response randomness

# Learning Settings
learning:
  enabled: true                       # Toggle learning system
  
  # Learning parameters
  pattern_threshold: 3                # Minimum patterns for learning
  success_threshold: 0.8              # Required success rate
  context_window: 5                   # Context history size
  max_patterns: 1000                  # Maximum stored patterns
  
  # Storage paths
  data_path: "cache/learning/learning.json"

# Router Settings
router:
  default_context: "general"          # Default conversation context
  fallback_context: "help"            # Context when errors occur
  max_history: 10                     # Maximum conversation history

# Logging Settings
logging:
  level: INFO
  file_rotation: "1 MB"
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Notes:
# - Audio uses ALSA (Advanced Linux Sound Architecture) directly
# - All volume levels use RMS values from 16-bit audio (0-32767)
#   - Ambient noise: ~200-800
#   - Normal speech: ~500-2000
#   - Loud speech: ~2000-4000
#   - Very loud/clipping: >4000
# - Calibrated for TONOR TM20 microphone
# - Recalibrate if microphone settings change
