# Skills Configuration
# -------------------
# Defines intents, patterns, and weights for all available skills

intents:
  # Base confidence scores for each intent type
  base_scores:
    story: 0.0        # No inherent bias
    education: 0.5    # Slight bias towards educational responses
    tutor: 0.0        # No inherent bias
    timer: 0.0        # No inherent bias
    conversation: 0.3 # Small bias to favor conversation when ambiguous

  # Pattern matching weights
  weights:
    conversation: 1.5  # Moderate boost for conversation markers
    timer: 2.0        # Strong boost - timer requests should be precise
    education: 1.5    # Moderate boost for learning queries
    story: 1.5        # Moderate boost for story requests
    tutor: 1.5        # Moderate boost for tutoring requests

  # Pattern matching for intent detection
  patterns:
    conversation:
      keywords:
        - "chat"
        - "talk" 
        - "speak"
        - "tell"
        - "say"
        - "hello"
        - "hi"
        - "hey"
        - "thanks"
        - "thank you"
        - "bye"
        - "goodbye"
        - "discuss"
        - "conversation"
      description: "General conversation and chat interactions"
      fallback: true  # Used when no strong match is found

    timer:
      keywords:
        - "timer"
        - "set timer"
        - "remind me"
        - "minutes"
        - "seconds"
        - "hours"
        - "wait"
        - "alarm"
        - "countdown"
      description: "Timer and reminder functionality"
      requires_params: true  # Needs duration parameter

    education:
      keywords:
        - "what"
        - "why"
        - "how"
        - "when"
        - "where"
        - "explain"
        - "tell me about"
        - "learn"
        - "teach"
        - "understand"
        - "mean"
        - "difference"
        - "help me"
        - "show me"
        - "example"
      description: "Educational queries and explanations"
      default: true  # Used when no clear intent is detected

    story:
      keywords:
        - "story"
        - "once upon"
        - "tale"
        - "adventure"
        - "bedtime"
        - "read"
        - "chapter"
        - "book"
      description: "Storytelling and narrative content"
      requires_context: true  # Uses conversation history

  # Intent detection thresholds
  thresholds:
    min_confidence: 0.5    # Minimum score to consider intent valid
    context_bonus: 1.0     # Added to score if matches current context

  # Intent transitions
  # Defines allowed transitions between intents
  transitions:
    education:
      - story           # Can transition to story examples
      - conversation    # Can shift to general discussion
    story:
      - education      # Can lead to learning opportunities
      - conversation   # Can discuss story elements
    conversation:
      - education     # Can spark learning questions
      - story        # Can lead to storytelling
    timer:
      - conversation # Can return to general chat
      - education   # Can explain time concepts